version: '2'
services:

  dev:
    build:
      context: ./
    image: muccg/bind:${GIT_BRANCH}

  prod:
    build:
      context: ./
    image: muccg/bind:stretch

  latest:
    extends:
      file: docker-compose-build.yml
      service: prod
    image: muccg/bind:latest
